version: '3.3'

services:

  api-gateway:
    container_name: api-gateway
    image: aleramiirez/generics:api-gateway
    ports:
      - 8084:8084
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:mysql://generics-sql-server.mysql.database.azure.com:3306/generics_sql?useSSL=true
      - DATABASE_USERNAME=aleramiirez
      - DATABASE_PASSWORD=Password0
    networks:
      - generics

  register-service:
    container_name: register-service
    image: aleramiirez/generics:register-service
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:mysql://generics-sql-server.mysql.database.azure.com:3306/generics_sql?useSSL=true
      - DATABASE_USERNAME=aleramiirez
      - DATABASE_PASSWORD=Password0
    depends_on:
      - api-gateway
    networks:
      - generics

  crud-service:
    container_name: crud-service
    image: aleramiirez/generics:crud-service
    ports:
      - 8082:8082
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:mysql://generics-sql-server.mysql.database.azure.com:3306/generics_sql?useSSL=true
      - DATABASE_USERNAME=aleramiirez
      - DATABASE_PASSWORD=Password0
    depends_on:
      - api-gateway
    networks:
      - generics

  generics-front:
    container_name: generics-front
    image: aleramiirez/generics:generics-front
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=jdbc:mysql://generics-sql-server.mysql.database.azure.com:3306/generics_sql?useSSL=true
      - DATABASE_USERNAME=aleramiirez
      - DATABASE_PASSWORD=Password0
    networks:
      - generics

networks:
  generics:
    driver: bridge