version: '4'

services:
  register-db:
    container_name: register-db
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestiongenerica
      PMA_HOST: mysql
    ports:
      - 3307:3306
    networks:
      - generics

  register-service:
    container_name: register-service
    image: register-service
    build: .
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=jdbc:mysql://register-db:3306/gestiongenerica?autoReconnect=true&useSSL=false
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    networks:
      - generics

  crud-service:
    container_name: crud-service
    image: crud-service
    build: .
    ports:
      - 8082:8082
    environment:
      - DATABASE_URL=jdbc:mysql://register-db:3306/gestiongenerica?autoReconnect=true&useSSL=false
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    networks:
      - generics

  discovery-server:
    container_name: discovery-server
    image: discovery-server
    build: .
    ports:
      - 8761:8761
    environment:
      - DATABASE_URL=jdbc:mysql://register-db:3306/gestiongenerica?autoReconnect=true&useSSL=false
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    networks:
      - generics

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://register-db:3306/gestiongenerica?autoReconnect=true&useSSL=false
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    networks:
      - generics

networks:
  generics:
    driver: bridge