spring:
  cloud:
    gateway:
      routes:
        - id: register-service
          # URL para despliege en local
          # uri: http://localhost:8081

          # URL para despliege con .jar
          # uri: http://20.229.96.216:8081

          # URL para despliegue con docker-compose
          uri: http://register-service:8081

          # URL para despliegue con kubernetes
          # uri: http://nlb-service.generics-namespace.svc.cluster.local:8081
          predicates:
            - Path=/auth/**

        - id: crud-service
          # URL para despliege en local
          # uri: http://localhost:8082

          # URL para despliege con .jar
          # uri: http://20.229.96.216:8082

          # URL para despliegue con docker-compose
          uri: http://crud-service:8082

          # URL para despliegue con kubernetes
          # uri: http://nlb-service.generics-namespace.svc.cluster.local:8082
          predicates:
            - Path=/api/v1/usuarios/**

          filters:
            - AuthenticationFilter


logging:
  level:
    com.viewnext.api_gateway.filter.AuditFilter: INFO


audit:
  log:
    path: C:\Desarrollo\GestionGenericaP\api-gateway\api_gateway_audit.log