spring:
  cloud:
    gateway:
      routes:
        - id: register-service
          uri: http://register-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - LoggingFilter

        - id: crud-service
          uri: http://crud-service:8082
          predicates:
            - Path=/api/v1/usuarios/**
          filters:
            - AuthenticationFilter
            - LoggingFilter
