spring:
  cloud:
    gateway:
      routes:
        - id: register-service
          uri: http://20.229.96.216:8081
          predicates:
            - Path=/auth/**

        - id: crud-service
          uri: http://20.229.96.216:8082
          predicates:
            - Path=/api/v1/usuarios/**

          filters:
            - AuthenticationFilter
