apiVersion: v1
kind: Service
metadata:
  name: generics-flow
  namespace: generics-namespace
spec:
  type: LoadBalancer
  selector:
    app: generics-flow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080