name: generics-flow
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  ACR_RESOURCE_GROUP: Generics-group
  AZURE_CONTAINER_REGISTRY: genericsrepository
  CLUSTER_NAME: generics-cluster
  CLUSTER_RESOURCE_GROUP: Generics-group
  CONTAINER_NAME: generics-deploy
  DEPLOYMENT_MANIFEST_PATH: |
    manifests/deployment.yaml
    manifests/service.yaml

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Build and push Docker images for api-gateway to azure
        run: |
          cd api-gateway
          docker build -t genericsrepository.azurecr.io/generics:api-gateway .
          docker push genericsrepository.azurecr.io/generics:api-gateway
      - name: Build and push Docker images for crud-service to azure
        run: |
          cd CRUD-service
          docker build -t genericsrepository.azurecr.io/generics:crud-service .
          docker push genericsrepository.azurecr.io/generics:crud-service
      - name: Build and push Docker images for register-service to azure
        run: |
          cd register-service
          docker build -t genericsrepository.azurecr.io/generics:register-service .
          docker push genericsrepository.azurecr.io/generics:register-service

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs:
      - buildImage
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - uses: azure/use-kubelogin@v1
        name: Set up kubelogin for non-interactive login
        with:
          kubelogin-version: v0.0.25
      - uses: azure/aks-set-context@v3
        name: Get K8s context
        with:
          admin: "false"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          use-kubelogin: "true"
      - uses: Azure/k8s-deploy@v4
        name: Deploys application
        with:
          action: deploy
          images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          namespace: generics-namespace
