# Actions

  name: Java CI with Maven

  on:
    push:
      branches: ['feature-ale-v.2']
    pull_request:
      branches: ['feature-ale-v.2']

  jobs:
    build:

      runs-on: ubuntu-latest

      steps:
        - name: Check out the repository
          uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Build and test with Maven
          run: mvn --batch-mode package
