# Este flujo de trabajo construirá un proyecto Java con Maven y cacheará/restaurará cualquier dependencia para mejorar el tiempo de ejecución del flujo de trabajo.
# Para obtener más información, consulta: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# Este flujo de trabajo utiliza acciones que no están certificadas por GitHub.
# Son proporcionadas por un tercero y están regidas por
# términos de servicio, política de privacidad y documentación de soporte
# separados.

name: Java CI con Maven

on:
  push:
    branches: [ "feature-alberto" ]
  pull_request:
    branches: [ "feature-alberto" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Construir y probar con Maven
        run: mvn --batch-mode package

  build-docker-images:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout del repositorio
        uses: actions/setup-java@v3

      - name: Construir imágenes de Docker
        run: |
          docker build -t api-gateway api-gateway
          docker build -t crud-service CRUD-service
          docker build -t discovery-server discovery-server
          docker build -t register-service register-service
